Repository SimpleAuthentication/SimpleAuthentication, pull requests merged in 2023-09, with the labels that each got.

#227 Update Core/ExtraProviders to NETStandard 2.0
  .gitignore
  Code/Nancy.SimpleAuthentication/Nancy.SimpleAuthentication.csproj
  Code/Nancy.SimpleAuthentication/SimpleAuthenticationModule.cs
  Code/Nancy.SimpleAuthentication/packages.config
  Code/SimpleAuthentication.Core/Config/ProviderConfigurationHelper.cs
  Code/SimpleAuthentication.Core/Csrf/AntiForgery.cs
  Code/SimpleAuthentication.Core/Csrf/IAntiForgery.cs
  Code/SimpleAuthentication.Core/Csrf/TokenData.cs
  Code/SimpleAuthentication.Core/Properties/AssemblyInfo.cs
  Code/SimpleAuthentication.Core/SimpleAuthentication.Core.csproj
  Code/SimpleAuthentication.Core/SimpleAuthentication.Core.csproj.DotSettings
  Code/SimpleAuthentication.Core/packages.config
  Code/SimpleAuthentication.ExtraProviders/BitBucket/AccessTokenResult.cs
  Code/SimpleAuthentication.ExtraProviders/BitBucket/BitBucketAuthenticationServiceSettings.cs
  Code/SimpleAuthentication.ExtraProviders/BitBucket/BitBucketProvider.cs
  Code/SimpleAuthentication.ExtraProviders/BitBucket/RequestTokenResult.cs
  Code/SimpleAuthentication.ExtraProviders/BitBucket/VerifierResult.cs
  Code/SimpleAuthentication.ExtraProviders/BitBucket/VerifyCredentialsResult.cs
  Code/SimpleAuthentication.ExtraProviders/Properties/AssemblyInfo.cs
  Code/SimpleAuthentication.ExtraProviders/SimpleAuthentication.ExtraProviders.csproj
  Code/SimpleAuthentication.ExtraProviders/packages.config
  Code/SimpleAuthentication.Mvc-3/SimpleAuthentication.Mvc-3.csproj
  Code/SimpleAuthentication.Mvc-3/app.config
  Code/SimpleAuthentication.Mvc-3/packages.config
  Code/SimpleAuthentication.Mvc/SimpleAuthentication.Mvc.csproj
  Code/SimpleAuthentication.Mvc/app.config
  Code/SimpleAuthentication.Mvc/packages.config
  NuGet/SimpleAuthentication.Core.nuspec
  NuGet/SimpleAuthentication.ExtraProviders.nuspec
  NuGet/SimpleAuthentication.Mvc-4.nuspec
  Samples/SimpleAuthentication.Sample.MvcAuto/GlimpseSecurityPolicy.cs
  Samples/SimpleAuthentication.Sample.MvcAuto/SimpleAuthentication.Sample.MvcAuto.csproj
  Samples/SimpleAuthentication.Sample.MvcAuto/Web.config
  Samples/SimpleAuthentication.Sample.NancyAuto/Modules/HomeModule.cs
  Samples/SimpleAuthentication.Sample.NancyAuto/SimpleAuthentication.Sample.NancyAuto.csproj
  Samples/SimpleAuthentication.Sample.NancyAuto/Web.config
  Samples/SimpleAuthentication.Sample.NancyAuto/packages.config
  SimpleAuthentication.sln.DotSettings
Labels: enhancement, breaking change

#228 🚮Don't need R# settings
  SimpleAuthentication.sln.DotSettings
Labels: enhancement

#229 😘 Gotta standardize the .NET version
  global.json
Labels: enhancement

#230 🚀 Lets have some GitHub actions!
  .github/workflows/MergeToMain.yml
  .github/workflows/PullRequest.yml
  .github/workflows/Release.yml
  AppVeyor/appveyor-master.yml
  AppVeyor/appveyor.yml
Labels: enhancement

#233 🎨 Fix up the NuGet meta info
  .github/workflows/MergeToMain.yml
  .github/workflows/PullRequest.yml
  Code/SimpleAuthentication.Core/SimpleAuthentication.Core.csproj
  Code/SimpleAuthentication.ExtraProviders/SimpleAuthentication.ExtraProviders.csproj
  Icon.jpg
  NuGet/ReadMe.txt
  NuGet/SimpleAuthentication.Core.nuspec
  NuGet/SimpleAuthentication.ExtraProviders.nuspec
Labels: enhancement, documentation
